"""add missing body measurement table

Revision ID: 5a508b1a62e1
Revises: f3513436e418
Create Date: 2026-09-15 15:10:58.271506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a508b1a62e1'
down_revision = 'f3513436e418'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_measured_at'), 'body_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_measured_at'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
