"""create users table

Revision ID: f3513436e418
Revises: None
Create Date: 2026-08-19 13:11:54.184546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3513436e418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_complete')
    # ### end Alembic commands ###
